### PR TITLE
add a new tool.

### PR DESCRIPTION
**Pull request by kamagatos**

### CODE REVIEW

**Comment by mpaik** [comment]
@kamagatos, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by kamagatos** [comment]
The agreement has been signed, but I think the commit is a little bit old. I'll send another PR.

**Comment by mpaik** [comment]
Closed pending new PR.

**Comment by kamagatos** [comment]
I patched this commit instead of creating a new PR, you can merge this one. Thanks

**Comment by mpaik** [comment]
Merged with edits.

**Pull request closed without merging**
