### PR TITLE
Update administration-interfaces.txt

### PR DESCRIPTION
**Pull request by spviewer**
Hi,

please submit changes to administration-interfaces.txt document. I have submitted information about our free software product NoSQL Viewer for MongoDB.

Thanks,
Alexey

### CODE REVIEW

**Comment by mpaik** [comment]
Merged with edits.

**Comment by spviewer** [comment]
Hi Michael,

please provide details if you added information about free NoSQL Viewer tool to tools list? thanks!

**Comment by mpaik** [comment]
https://github.com/mongodb/docs-ecosystem/commit/697c7f043a4966f8d00af5ab9743f46367ac365e

**Comment by spviewer** [comment]
thanks but I do not see this change here http://docs.mongodb.org/ecosystem/tools/administration-interfaces/

**Comment by mpaik** [comment]
We do not publish on-demand but as necessary. The change will be in the next publication cycle.

**Pull request closed without merging**
