### PR TITLE
DOCS-10884: Update driver compatibility for PyMongo 3.5 release

### PR DESCRIPTION
**Pull request by stennie**

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Thanks @stennie! I think this looks good but is it possible to put up a rendered view to make sure?

**Comment by stennie** [comment]
@ShaneHarvey Rendered versions:
 - [Python Driver](https://s3.amazonaws.com/stennie-docs-pr/DOCS-10884/drivers/python.html#python-driver-compatibility)
 - [Python Driver Compatibility](https://s3.amazonaws.com/stennie-docs-pr/DOCS-10884/drivers/driver-compatibility-reference.html#python-driver-compatibility)

Cheers,
Stennie

**Comment by ShaneHarvey** [comment]
Thanks! Would you mind also updating the Motor documentation? 

Motor 1.1 needs to be added which supports Python 2.7, 3.3, 3.4, 3.5, and 3.6. It dropped support for Python 2.6. 
Motor 1.1  wraps PyMongo 3.4+.

Motor 1.0 also supports Python 3.6.

**Comment by stennie** [comment]
@ShaneHarvey Added Motor 1.1 details per your comment.

Rendered versions:

 - [Motor Driver](https://s3.amazonaws.com/stennie-docs-pr/DOCS-10884/drivers/python.html#id1)
 - [Motor Driver Compatibility Reference](https://s3.amazonaws.com/stennie-docs-pr/DOCS-10884/drivers/driver-compatibility-reference.html#motor-driver-compatibility)

Cheers,
Stennie

**Comment by ShaneHarvey** [comment]
Thanks!

**Pull request merged**
