### PR TITLE
Add Eve (Python) REST API Framework

### PR DESCRIPTION
**Pull request by nicolaiarocci**
Eve allows to easily build and deploy fully powered REST Web Services backed by MongoDB.

### CODE REVIEW

**Comment by kay-kim** [comment]
Hello -- thank you for this pull request and apologies for the huge delay. We'll get to this pull request shortly, but before we merge this, could you sign the Contributor Agreement found at https://www.mongodb.com/legal/contributor-agreement?

Regards,

Kay Kim

**Comment by nicolaiarocci** [comment]
Done.

**Comment by kay-kim** [comment]
Merged.  Thank you.

**Comment by nicolaiarocci** [comment]
@kay-kim I added the missing resource link, which was missing from this PR. Sorry about that. See #332.

**Pull request closed without merging**
