### PR TITLE
Add Mongolastic into the app list

### PR DESCRIPTION
**Pull request by ozlerhakan**
Hi,

Here is the tool called mongolastic to clone data between mongodb and elasticsearch. I hope the tool is proper for the mongodb community.

### CODE REVIEW

**Comment by kay-kim** [comment]
Hello -- thank you for this pull request and apologies for the huge delay. We'll get to this pull request shortly, but before we merge this, could you sign the Contributor Agreement found at https://www.mongodb.com/legal/contributor-agreement?

Regards,

Kay Km

**Comment by ozlerhakan** [comment]
Hi @kay-kim ,

That's okay, I have signed it.

**Comment by kay-kim** [comment]
Thank you.  This has been merged and published.

**Comment by ozlerhakan** [comment]
Thanks!

cc: @hakdogan

**Pull request closed without merging**
