### PR TITLE
Add reference to Mongolia

### PR DESCRIPTION
**Pull request by nilskp**
[Review on Reviewable](https://reviewable.io/reviews/mongodb/docs-ecosystem/264)

### CODE REVIEW

**Comment by mpaik** [comment]
@nilskp, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by nilskp** [comment]
@mpaik, done.

**Comment by mpaik** [comment]
Merged with minor edits.

**Comment by mpaik** [comment]
The listings of tools in the ecosystem is being deprecated and moved to http://mongodb-tools.com/, please submit your listing there.

**Pull request closed without merging**
