### PR TITLE
Update administration-interfaces.txt

### PR DESCRIPTION
**Pull request by phpmongodb**

### CODE REVIEW

**Comment by mpaik** [comment]
@phpmongodb, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by phpmongodb** [comment]
@mpaik Thanks

**Comment by phpmongodb** [comment]
@mpaik i have not added image in document may add image url.

**Comment by mpaik** [comment]
Merged with edits

**Pull request closed without merging**
