### PR TITLE
MongoDB support for Django

### PR DESCRIPTION
**Pull request by nesdis**
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs-ecosystem/428)

### CODE REVIEW

**Comment by nesdis** [comment]
Hello @kay-kim. As requested a new pull request.

**Comment by kay-kim** [comment]
Thank you.  Will publish tomorrow.

**Comment by nesdis** [comment]
Thank you @kay-kim

**Comment by nesdis** [comment]
Hello @kay-kim I was wondering, when do the merged changes get built and published on the main web-page?

**Comment by nesdis** [comment]
@kay-kim is there something else I need to do for the merged changes to get published?

**Comment by kay-kim** [comment]
Hi @nesdis  -- this was published already.  You might have to hard refresh.  Let me know if you don't see it.

**Comment by nesdis** [comment]
@kay-kim Got it!! Thank you for your quick and prompt response! 👍

**Comment by kay-kim** [comment]
👍

**Pull request merged**
