### PR TITLE
Add jenssegers/laravel-mongodb to the list

### PR DESCRIPTION
**Pull request by duxet**
It's popular package for Laravel framework.

### CODE REVIEW

**Comment by mpaik** [comment]
@duxet, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by duxet** [comment]
@mpaik done :)

**Comment by mpaik** [comment]
Merged with edits.

**Comment by mpaik** [comment]
The listings of tools in the ecosystem is being deprecated and moved to http://mongodb-tools.com/, please submit your listing there.

**Pull request closed without merging**
