### PR TITLE
Add Morphix to POJO mappers

### PR DESCRIPTION
**Pull request by ParaPenguin**
Just finished working on the basic features for [Morphix](https://github.com/ParaPenguin) because Morphia doesn't include a cache, and I've had issues with Morphium's caching system.

**Note:** this project is still a work in progress, however the basic features (querying, mapping and caching) all work fine.

### CODE REVIEW

**Comment by kblanks** [comment]
:+1:

**Comment by mpaik** [comment]
@ParaPenguin, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by mpaik** [comment]
Merged with edits

**Comment by mpaik** [comment]
The listings of tools in the ecosystem is being deprecated and moved to http://mongodb-tools.com/, please submit your listing there.

**Pull request closed without merging**
