### PR TITLE
Added MongoFS library reference to Java page

### PR DESCRIPTION
**Pull request by dbuschman7**

### CODE REVIEW

**Comment by mpaik** [comment]
@dbuschman7, please sign the MongoDB Contributor Agreement (https://www.mongodb.com/legal/contributor-agreement) and forward the .pdf to docs@10gen.com for merge of this pull request. Thanks!

**Comment by dbuschman7** [comment]
Done

Thanks
   DaVe.

**Comment by mpaik** [comment]
PDF not yet received; did you forward the confirmation?

**Comment by dbuschman7** [comment]
I just forwarded it

Thanks
   DaVe.

**Comment by mpaik** [comment]
Confirmation still not received.

**Comment by mpaik** [comment]
Squashed + merged with edits.

**Pull request closed without merging**
