### PR TITLE
Update Ruby driver tutorial to include example using a tailable cursor

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by kay-kim** [comment]
@steveren  -- just double checking if this example is included in your rewrite.

**Comment by estolfo** [comment]
I believe it is, but I'll let @steveren confirm.

**Comment by steveren** [comment]
Yes, there's a subsection on Tailable Cursors in the CRUD operations
section in the latest staged version.

**Comment by estolfo** [comment]
Thanks for confirming, @steveren, I'll close this.

**Pull request closed without merging**
