### PR TITLE
Add DigitalOcean to the Platforms section.

### PR DESCRIPTION
**Pull request by andrewsomething**
This adds details on using MongoDB on DigitalOcean to the Platforms section of the documentation. I kept it simple as going into details about how to use MongoDB itself (as some of the other providers covered do) seems a bit redundant. Let me know if the voice is ok, the different providers seem to vary in tone.

I'll open a corresponding PR against https://github.com/mongodb/docs-assets/tree/ecosystem for the image.

digitalocean-control-panel

Thanks!

### CODE REVIEW

**Comment by mpaik** [comment]
Andrew, we're preparing to merge this, but you'll need to sign the Contributor Agreement at https://www.mongodb.com/legal/contributor-agreement and email a copy to DocsTeam@mongodb.com.

**Comment by andrewsomething** [comment]
@mpaik Signed and sent. Thanks!

**Comment by andrewsomething** [comment]
Hmm... Email to DocsTeam@mongodb.com seems to bounce.

**Comment by mpaik** [comment]
Make that docs@10gen.com (the aliases can get a little finicky)

**Comment by andrewsomething** [comment]
Sent the signed agreement to docs@10gen.com Also updated both pull requests to reflect that we are now offering 3.0 rather than the 2.6 series.

**Comment by mpaik** [comment]
Merged with minor copy edit. Cheers!

**Pull request closed without merging**
